# Change these first
owner: cleydyr # Your GitHub organization or username, where this repository lives
repo: biblivre-cloud-upptime # The name of this repository

sites:
  - name: Biblivre Baixada Literária
    url: https://baixadaliteraria.biblivre.cloud
  - name: Releitura Pernambuco
    url: https://releiturape.biblivre.cloud
  - name: Biblioteca Municipal Celso Brant
    url: https://trespontas.biblivre.cloud
  - name: Associação São Roque
    url: https://associacaosaoroque.biblivre.cloud
  - name: Solar dos Abacaxis
    url: https://solardosabacaxis.biblivre.cloud
  - name: Instituto Luzia Basílio
    url: https://institutoluziabasilio.biblivre.cloud/
  - name: Biblioteca Teste
    url: https://associacaosaoroque.biblivre.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.biblivre.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Biblivre Cloud Upptime
  introTitle: Biblivre Cloud Status Page
  introMessage: Estado das instâncias do Biblivre Cloud
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
